// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8536a77jKUAodw44MNsv2KKn7HKIDT0',
    appId: '1:1046245241778:web:3ed69d8a377299a521aaab',
    messagingSenderId: '1046245241778',
    projectId: 'programsiramtanamotomatisb',
    authDomain: 'programsiramtanamotomatisb.firebaseapp.com',
    databaseURL: 'https://programsiramtanamotomatisb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatisb.firebasestorage.app',
    measurementId: 'G-BY1YDGVEJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3U0VIltL-N0m8btw0vfBiyrL4oHekWs',
    appId: '1:1046245241778:android:936d7510fdcad4b221aaab',
    messagingSenderId: '1046245241778',
    projectId: 'programsiramtanamotomatisb',
    databaseURL: 'https://programsiramtanamotomatisb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatisb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12ON0qYyMGxuA4rgn9kir5gdMAFF13C4',
    appId: '1:1046245241778:ios:c178f49ef0396d5821aaab',
    messagingSenderId: '1046245241778',
    projectId: 'programsiramtanamotomatisb',
    databaseURL: 'https://programsiramtanamotomatisb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatisb.firebasestorage.app',
    iosBundleId: 'com.example.aiteknoSmartfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12ON0qYyMGxuA4rgn9kir5gdMAFF13C4',
    appId: '1:1046245241778:ios:c178f49ef0396d5821aaab',
    messagingSenderId: '1046245241778',
    projectId: 'programsiramtanamotomatisb',
    databaseURL: 'https://programsiramtanamotomatisb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatisb.firebasestorage.app',
    iosBundleId: 'com.example.aiteknoSmartfarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX8536a77jKUAodw44MNsv2KKn7HKIDT0',
    appId: '1:1046245241778:web:340541739247d4ea21aaab',
    messagingSenderId: '1046245241778',
    projectId: 'programsiramtanamotomatisb',
    authDomain: 'programsiramtanamotomatisb.firebaseapp.com',
    databaseURL: 'https://programsiramtanamotomatisb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatisb.firebasestorage.app',
    measurementId: 'G-N26C9N76PS',
  );
}
